# Generated by Django 4.0 on 2022-05-19 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
