# Generated by Django 4.0 on 2022-05-23 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_bibleverse"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(blank=True),
        ),
    ]
