# Generated by Django 4.0 on 2022-03-29 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='fake-slug'),
            preserve_default=False,
        ),
    ]
