# Generated by Django 4.0 on 2022-05-19 22:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0002_donation_paid"),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="ref_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
